# Generated by Django 5.0 on 2024-01-23 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppHealthy', '0003_avatarimangen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvatarImangen',
            new_name='Avatar',
        ),
    ]
